# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 26bc1f0c38a93e3f86dd2f085c02d49618488fbc7a662b6c1e9c6156cbd59a29f3e263bae4ab327e71d1fa8716b3d416a69ce32ff145efaf93fab54743b10ae7

test:
  secret_key_base: 68230d3c46b3b89faf47573414eae62c7b11ec11c789582be4ab3242bd32e841183be6f96d11b3272ce9eaba0df8bc1666a2d5bc6136922084f5936456de5e2b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
